FROM theflash2k/pwn-chal:latest

ENV CHAL_NAME=Birdy101
COPY ${CHAL_NAME} .
COPY ld-2.35.so ld-2.35.so
COPY libc.so.6 libc.so.6
EXPOSE 8000

# For dynamic flagging:
COPY docker-entrypoint.sh /tmp/docker-entrypoint.sh
RUN chmod +x /tmp/docker-entrypoint.sh
ENTRYPOINT [ "/tmp/docker-entrypoint.sh" ]
